var pavardesPL = new Map([
["Abalewicz", "Obuolënas"],
["Akuc", "Akutis"],
["Akuto", "Akutis"],
["Akutowicz", "Akutavièius"],
["Andrukianec", "Andrukënas"],
["Aszakiewicz", "Aðaka"],
["Aszaki", "Aðaka"],
["Aszakow", "Aðaka"],
["Aszkieùojc", "Oðkelaitis"],
["Aszkieùowicz ", "Oðkelis"],
["Auksztolis", "Aukðtuolis"],
["Awgul", "Augulis"],
["Awiþen", "Aviþienis"],
["Baczul", "Baèiulis"],
["Baltuc", "Baltutis"],
["Balul", "Baliulis"],
["Banul", "Baniulis"],
["Biedulski", "Bëdulis"],
["Bit", "Bitë"],
["Bitowt", "Bytautas"],
["Bohdziul", "Bagdþiulis"],
["Bolcewicz", "Balèius"],
["Bolsiewicz", "Balsys"],
["Boùtuc", "Baltutis"],
["Bombol", "Bumbulas"],
["Cenin", "Tininis"],
["Ciesiun", "Tiesiûnas"],
["Ciunajtis", "Tijûnaitis"],
["Ciwil", "Èivylis"],
["Clewinski", "Klevinis"],
["Curlanis", "Èiurlionis"],
["Czeþyk", "Dagilis"],
["Czywil", "Èivylis"],
["Czusnojc", "Èesnaitis"],
["Darwid", "Darvydas"],
["Deguc", "Degutis"],
["Dywejko", "Deveika"],
["Dojlidko", "Dailidë"],
["Dowgelo", "Daugëla"],
["Dowgierd", "Daugirdas"],
["Downarowicz", "Daunoras"],
["Dremo", "Drëma"],
["Drozd", "Strazdas"],
["Drutel", "Drûtelis"],
["Dudojc", "Dûdaitis"],
["Dwilewicz", "Dvylis"],
["Dziadulewicz", "Diedulis"],
["Dziatùowski", "Genys"],
["Dziaugis", "Dþiaugys"],
["Dziedziul", "Didþiulis"],
["Dzieguc", "Degutis"],
["Dzierþyc", "Dirþys"],
["Dzierþynski", "Dirþys"],
["Dziewialtowicz", "Deltuva"],
["Dziewulski", "Dievulis"],
["Dzidziul", "Didþiulis"],
["Dzwil", "Dvylis"],
["Drzewenis", "Dievenis"],
["Ejsmont", "Eismantas"],
["Ejtminowicz", "Eitminas"],
["Gejdel", "Gaidelis"],
["Gejgal", "Gaigalas"],
["Giedrojc", "Giedraitis"],
["Gieguc", "Gegutis"],
["Giejsztowt", "Geistautas"],
["Giruc", "Girutis"],
["Goidz", "Gaidys"],
["Golmont", "Galmantas"],
["Gotowt", "Gotautas"],
["Grawþel", "Grauþelis"],
["Grodz", "Gruodis"],
["Gudalun", "Gudeliûnas"],
["Hruzd", "Gruzdas"],
["Huss", "Ûsas"],
["Ilgiewicz", "Ilgis (Ilgevièius)"],
["Jackiewicz", "Jackus (Jackevièius)"],
["Jackun", "Jackûnas"],
["Jagieùùowicz", "Jogëla (Jagelovièius)"],
["Jaglinski", "Eglë (Jaglinskis)"],
["Jakubenas", "Jokûbënas (Jakûbënas)"],
["Jakucun", "Jakuèiûnas"],
["Jakutojc", "Jakutaitis (Jakutoicis)"],
["Jananiec", "Janonis (Jananecas)"],
["Jankun", "Jankûnas"],
["Janukojc", "Janukaitis (Janukoicis)"],
["Jodel", "Juodelis (Jodelis)"],
["Jodelis", "Juodelis"],
["Jodelo", "Juodelë (Jodela)"],
["Jodkelo", "Juodkelë (Jodkela)"],
["Josiel", "Jaselis (Joselis)"],
["Judeiko", "Juodeika (Judeika)"],
["Klewialo", "Klevelis (Kleviala)"],
["Klukojc", "Kliukaitis (Klukoicis)"],
["Konopienis", "Kanapienis (Konopienis)"],
["Kontowt", "Kantautas (Kontovtas)"],
["Kordel", "Kardelis (Kordelis)"],
["Korejwo", "Kareiva (Koreiva)"],
["Korwiel", "Karvelis (Korvelis)"],
["Kadziul", "Kadþiulis (Kadziulis)"],
["Kanapka", "Kanapë (Kanapka)"],
["Kapusto", "Kopûstas (Kapusta)"],
["Karalun", "Karaliûnas"],
["Kardis", "Kardys (Kardis)"],
["Kardzis", "Kardys (Kardis)"],
["Karol", "Karalius (Karolis)"],
["Karuþel", "Karuþëlis"],
["Katin", "Katinas"],
["Kawalun", "Kavoliûnas (Kavaliûnas)"],
["Kawszyn", "Kauðinis (Kavðinis)"],
["Kewol", "Këvalas (Kevalas)"],
["Kæpiñski", "Kempë (Kempinskis)"],
["Kæstowicz", "Kæstaitis (Kenstovièius)"],
["Kibort", "Kybartas (Kibortas)"],
["Kiel", "Kielë (Kiela)"],
["Kielotis ", "Keliuotis"],
["Kosy", "Kuosa"],
["Kowal", "Kavolius"],
["Krawczun", "Kriauèiûnas (Kravèiûnas)"],
["Ùabuc", "Labutis (Labucis)"],
["Lazar", "Lozorius"],
["Mackalo", "Mackelë (Mackala)"],
["Mackaniec", "Mackonis (Mackanecas)"],
["Naruniec", "Narûnas"],
["Narwojsz", "Norvaiða"],
["Okinczyc", "Akinis"],
["Osinski", "Uosis"],
["Oszako", "Aðaka"],
["Okuñ", "Eðerys"],
["Pieczul", "Peèiulis"],
["Pietruc", "Petrutis"],
["Plawgo", "Pliauga"],
["Rajs", "Rojus"],
["Rydzel", "Ridelis"],
["Rynkun", "Rinkûnas"],
["Rodz", "Radys"],
["Rogiel", "Ragelis"],
["Rudak", "Rudokas"],
["Rudzis", "Rudys"],
["Rukojc", "Rûkaitis"],
["Sawlan", "Saulënas"],
["Siewruk", "Siaurukas"],
["Skorol", "Skarulis"],
["Szarejko", "Ðereika"],
["Szarelis", "Ðerelis"],
["Szarko", "Ðarka"],
["Szaszuro", "Ðeðiûra"],
["Szaukszto", "Ðaukðtas"],
["Szauksztun", "Ðaukðtûnas"],
["Szawejko", "Ðaveika"],
["Szawelo", "Ðavelis"],
["Szawlis", "Ðaulys"],
["Szawùowski", "Ðaulaitis"],
["Szczæsny", "Èësna"],
["Szczænowicz", "Èësnaitis"],
["Szczyùo", "Dagilis"],
["Szejbak", "Ðeibokas"],
["Szejnink", "Ðeiningas"],
["Szejpun", "Ðaipûnas"],
["Szejwalo", "Ðeivelë"],
["Szekalis", "Ðakelis"],
["Szelejko", "Ðileika"],
["Szemianowski", "Ðimënas"],
["Szepecki", "Ðepetys"],
["Szepetynski", "Ðepetys"],
["Szer", "Ðerys"],
["Szerytowicz", "Ðerytis"],
["Szeszko", "Ðeðkas"],
["Szewczuk", "Ðiauèiukas"],
["Szewiel", "Ðavelis"],
["Szydejkis", "Ðideikis"],
["Szykuc", "Ðikutis"],
["Szykulski", "Ðikulis"],
["Szyùejko", "Ðileika"],
["Szymanel", "Ðimonëlis"],
["Szymaniec", "Ðimonis"],
["Szymanowicz", "Ðimonis"],
["Szymanec", "Ðimënas"],
["Szymiel", "Ðimelis"],
["Szimkun", "Ðimkûnas"],
["Szymon", "Ðimonis"],
["Szymonowicz", "Ðimonis"],
["Szymukojc", "Ðimukaitis"],
["Szymukowicz", "Ðimukas"],
["Szirwinski", "Ðirvys"],
["Szlaz", "Ðleþas"],
["Szmatowicz", "Ðmotaitis"],
["Szmilgin", "Smilginis"],
["Szolno", "Ðalna"],
["Szostak", "Ðeðtokas"],
["Szostakowski", "Ðeðtokas"],
["Szpak", "Ðpokas"],
["Szpakowski", "Ðpokas"],
["Szpurgis", "Spurgis"],
["Szruba", "Sriuba"],
["Szugzdzin", "Ðiugþdinis"],
["Szukiel", "Ðukelis"],
["Szukszta", "Ðiukðta"],
["Szukszto", "Ðiukðta"],
["Szuksztelo", "Ðiukðtelë"],
["Szuksztul", "Ðiukðtulis"],
["Szuùobryt", "Ðulabritas"],
["Szumiel", "Ðumelis"],
["Szumielewski", "Ðumelis"],
["Szunejko", "Ðuneika"],
["Szuniewicz", "Ðunënas"],
["Szwinto", "Ðventys"],
["Talun", "Toliûnas"],
["Tamkun", "Tomkûnas"],
["Tankielun", "Tankieliûnas"],
["Tatol", "Tëtulis"],
["Taukin", "Taukinis"],
["Tawrel", "Taurelis"],
["Terlecki", "Terlys"],
["Tyliczan", "Telyèënas"],
["Tyllo", "Tyla"],
["Tyndalo", "Tindelë"],
["Tintin", "Tintinis"],
["Titaniec", "Titonis (Tetënas)"],
["Tytusz", "Tetuðis"],
["Tobola", "Tabala"],
["Tomaszun ", "Tamoðiûnas"],
["Towjanski", "Taujenis"],
["Trabszo", "Trepðys"],
["Trabuc", "Trobutis"],
["Trajanowicz", "Treinys"],
["Trakinski", "Trakinis"],
["Trapczys", "Trepðys"],
["Trasiulewicz", "Trasiulis"],
["Traszko", "Treðka"],
["Tretynkiewicz", "Tretinis"],
["Trynkun", "Trinkûnas"],
["Trypucki", "Triputis"],
["Trocki", "Trakys"],
["Trumpakajs", "Trumpakojis"],
["Trumpakajis", "Trumpakojis"],
["Trzeciak", "Treèiokas"],
["Tulejki", "Toleikis"],
["Tumialojc", "Tumelaitis"],
["Twirbut", "Tvirbutas"],
["Udrisz", "Ûdrys"],
["Ulbin", "Ulbinas"],
["Us", "Ûsas"],
["Ussel", "Ûselis"],
["Uþaloviè", "Àþuolaitis"],
["Uþdel", "Uþdëlis"],
["Uþwaùk", "Uþvalkas"],
["Wajszkun", "Vaiðkûnas"],
["Wojszkun", "Vaiðkûnas"],
["Wakor", "Vakaras"],
["Wanag", "Vanagas"],
["Wanagiel", "Vanagëlis"],
["Warþagalis", "Varþagalys"],
["Wasiùojc", "Vosylaitis"],
["Waszkojc", "Vaðkaitis"],
["Wawer", "Voverys"],
["Wawierowicz", "Voverys"],
["Wejksznia", "Vaikðnys"],
["Weryk", "Vërikas"],
["Wertynski", "Vertys"],
["Wæckiewicz", "Venckus"],
["Wiciun", "Vièiûnas"],
["Widuta", "Vidutis"],
["Widuto", "Vidutis"],
["Widziun", "Vidþiûnas"],
["Wiejalis", "Vëjelis"],
["Wierbun", "Verbûnas"],
["Wierszalowicz", "Verðelaitis"],
["Wiesztort", "Vieðtartas"],
["Wieszun", "Vieðiûnas"],
["Wieþalis", "Vëþelis"],
["Wieþynis", "Vëþinis"],
["Wyjalis", "Vëjelis"],
["Wikszta", "Vykðta"],
["Wikszto", "Vykðta"],
["Wilk", "Vilkas"],
["Wilkiewicz", "Vilkënas"],
["Wilkinski", "Vilkinis"],
["Wilkojc", "Vilkaitis"],
["Wimunc", "Vymantis"],
["Winceùojc", "Vincelaitis"],
["Winciaùojc", "Vincelaitis"],
["Winciun", "Vinciûnas"],
["Wincùaw", "Venclova"],
["Winsùaw", "Venclova"],
["Wirpszo", "Virpða"],
["Wirszyla", "Virðila"],
["Wirszub", "Virðupis"],
["Witkun", "Vitkûnas"],
["Witowcz", "Vytauèius"],
["Wiþyn", "Vyþinis"],
["Wizyn", "Vyþinis"],
["Wiþynis", "Vyþinis"],
["Wobalis", "Vabolys"],
["Wojciulewicz", "Vaièiulis"],
["Wojdat", "Vaidotas"],
["Wojeiki", "Vajeika"],
["Wojniùùo", "Vainyla"],
["Wojnisz", "Vainys"],
["Wojniusz", "Vainius"],
["Wojsiat", "Vaisieta"],
["Wojsiet", "Vaisieta"],
["Wosznarowicz", "Vaiðnora (Vaiðnoras)"],
["Wojszwiùùo", "Vaiðvila"],
["Zapolski", "Galinis"],
["Zastowt", "Þostautas"],
["Zygmont", "Þygmantas"],
["Zygmunt", "Þygmantas"],
["Zuj", "Zujus"],
["Zwereùùo ", "Þvërelë"],
["Þagiel", "Þagelis"],
["Þagun", "Þagûnas"],
["Þamojcin", "Þemaitynas"],
["Þamojdzin", "Þemaitynas"],
["Þamajc", "Þemaitis"],
["Þamojc", "Þemaitis"],
["Þamajtis", "Þemaitis"],
["Þamojtis", "Þemaitis"],
["Þardzin", "Þardynas"],
["Þebaùowicz", "Þebelionis"],
["Þebrowski", "Þebrionis"],
["Þelmo", "Þelmuo (Þelma)"],
["Þemojtel", "Þemaitëlis"],
["Þybik", "Þibikas"],
["Þydanis", "Þidonis"],
["Þi)giel", "Þygelis"],
["Þygiel", "Þygelis"],
["Þygielewicz", "Þygelis"],
["Þygiewicz", "Þygas"],
["Þygo", "Þygas"],
["Þuguè", "Þygutis"],
["Þylewicz", "Þilys"],
["Þiùo", "Þylë"],
["Þylojc", "Þilaitis"],
["Þyndul", "Þindulis"],
["Þynel", "Þinelis"],
["Þyngel", "Þingelis"],
["Þuwialo", "Þuvelë"],
["Þwalowski", "Þvalys"],
["Þwirblanski", "Þvirblaitis"],
["Þwireùùo", "Þvërelë"]
]);